### ISSUE TITLE
No support for `crafting_shapeless` recipes

### ISSUE THREAD

**Issue by GrantGryczan** [TheMrZZ/sandstone#127]
![image](https://user-images.githubusercontent.com/14056899/146432910-39cd6226-4470-4e45-81b2-f833d81fdf6b.png)

**Comment by TheMrZZ** [comment]
There should be support for it. You just need to specify other properties I believe.

**Comment by GrantGryczan** [comment]
The only place where the text `crafting_shapeless` shows up anywhere in Sandstone is in a comment.
