### ISSUE TITLE
`loot` command doesn't accept loot tables

### ISSUE THREAD

**Issue by GrantGryczan** [TheMrZZ/sandstone#130]
![image](https://user-images.githubusercontent.com/14056899/146468749-aef4986c-7d4c-429a-b4f6-d9c5c07b1773.png)

**Comment by TheMrZZ** [comment]
Why don't you use the builtin method `myLootTable.give('@a')`?

I will still fix it, but using the builtin method is better here.

**Comment by GrantGryczan** [comment]
Closer to vanilla syntax => more readable to people outside the project
