### ISSUE TITLE
Missing `run` in while statement

### ISSUE THREAD

**Issue by misode** [TheMrZZ/sandstone#19]
![image](https://user-images.githubusercontent.com/17352009/95229814-580a6d80-0801-11eb-81e3-16abd14f4c59.png)
![image](https://user-images.githubusercontent.com/17352009/95229759-445f0700-0801-11eb-9550-7f8c98484735.png)

**Comment by TheMrZZ** [comment]
Thanks for the report. I was able to reproduce this bug, and fixed it in #20 .
You can update using `npm install sandstone@latest` (or `yarn add sandstone@latest` if you're using yarn).
