### ISSUE TITLE
Comment utility does not correctly evaluate newlines

### ISSUE THREAD

**Issue by MulverineX** [TheMrZZ/sandstone#45]
```js
$('# Exclusive Inputs\n', 
  'Backward')
```
expected evaluation:
```haskell
# # Exclusive Inputs
# Backward
```

received evaluation:
```haskell
# # Exclusive Inputs
 Backward
```

**Comment by TheMrZZ** [comment]
Fixed in the next update. Btw, you don't need to put the #, Sandstone does it itself!

**Comment by MulverineX** [comment]
@TheMrZZ I am aware! The use of # was intentional to achieve what's in the expected evaluation, as a header comment of sorts.
