### ISSUE TITLE
Lack of player score copying

### ISSUE THREAD

**Issue by MulverineX** [TheMrZZ/sandstone#46]
`Scoreboard` `operation` does not accept `PlayerScore`, and `PlayerScore.set` does not accept another `PlayerScore`.

**Comment by TheMrZZ** [comment]
Ok for `scoreboard operation`, but I don't think I will add it.

`PlayerScore.set` actually accepts a PlayerScore. Can you show me a snippet of non-working code?

This works:
```ts
import { MCFunction } from "sandstone/core";
import { createObjective } from "../../sandstone/dist/variables";

MCFunction('test', () => {
  const myObjective = createObjective('test', 'dummy')
  const myPlayerScore1 = myObjective.ScoreHolder('@s')
  const myPlayerScore2 = myObjective.ScoreHolder('@r')
  myPlayerScore1.set(myPlayerScore2)
})
```

**Comment by MulverineX** [comment]
OH, the PlayerScore usage is an overload of `set`, not a `|` of `number` as I was expecting. Enormous brain.
