### ISSUE TITLE
_.if result score ids are not hashed

### ISSUE THREAD

**Issue by MulverineX** [TheMrZZ/sandstone#47]
![image](https://user-images.githubusercontent.com/12068027/102563146-e1f27480-4095-11eb-8473-520f3d588f1e.png)
This happens when building the pack, with as seen no changes made to the project source.

**Comment by TheMrZZ** [comment]
Can you show me the code resulting in this bug?

**Comment by MulverineX** [comment]
It happens for any usage of `_.if` period. Literally just use one and it does this

**Comment by TheMrZZ** [comment]
Fixed in the next update.
